#install.packages("aplpack")
library(aplpack)

# type the path to the data here
directory <- "c:/Users/sam29/Projects/R/Data-Analysis-in-R/DataVisualization/Amounts of waste generated by sector.csv"
garbage <- read.csv(directory, na.strings="..")

# transpose our dataframe
tmp <- t(garbage[, -1])

# now columns - types of garbage
colnames(tmp) <- garbage$Waste

# using library function on 3, 4, 6, ... columns of dataset
faces(tmp[, c(3, 4, 6, 7, 9, 10, 13, 14, 15, 16, 20, 24, 25, 27, 28)],
      labels=c(2000:2013), face.type=0,
      main="Amounts of waste generated by sector 1995-2013")
